jimengio/meson-form

example/pages/container.tsx, package.json, src/form.tsx, src/model/types.ts, yarn.lock
```type DemoKey = keyof IDemo;
let formItems: IMesonFieldItem<keyof DemoKey>[] = []
```
=> add generic type for field name

example/pages/container.tsx, package.json, src/form.tsx
Support customizing rendering of footer.
=> Customized footer renderer

example/pages/container.tsx, package.json, src/form.tsx, src/model/types.ts
Added new property `submitOnEdit` to tell form to submit after every modification. There might be edge cases for custom fields, which need to be handled in future.
=> New method submit on edit

example/pages/container.tsx, example/pages/select-page.tsx, src/form.tsx, src/model/types.ts
`Select` element prints warnings for boolean values. Provide a manual way to disable it.
=> provide a way to fix warning of select value type; add several props

example/forms/auto-save.tsx, example/forms/basic.tsx, example/forms/custom.tsx, example/forms/draft.tsx, example/forms/modal.tsx, example/forms/select-page.tsx, example/forms/validation.tsx, example/kits/source-link.tsx
=> link examples to source code

package.json, yarn.lock
=> free version of use-immer; alpha release

src/form.tsx
modal默认存在右上角的叉,可以通过hideClose控制。
=> add hideClose for meson modal

example/controller/generated-router.ts, example/forms/inline-form.tsx, example/models/router-rules.ts, example/pages/container.tsx, package.json, src/inline-form.tsx
Example http://fe.jimu.io/meson-form/#inline-form
=> Early example for inline-form

src/form.tsx
`renderFooter?: (isLoading: boolean, onSubmit: () => void, onCancel: () => void, from?: any) => ReactNode;`
=> feat: update renderFooter args

example/controller/generated-router.ts, example/forms/blank-label.tsx, example/models/router-rules.ts, example/pages/container.tsx, package.json, src/form.tsx, src/model/types.ts
Example http://fe.jimu.io/meson-form/#blank-label
Just set `null` to label.
```bash
yarn add @jimengio/meson-form@0.1.19-a1
```
=> support for blank labels

example/forms/inline-form.tsx, package.json, src/inline-form.tsx
Demo http://fe.jimu.io/meson-form/#inline-form
=> some base style for inline select; alpha release

README.md, example/forms/drawer.tsx, example/forms/modal.tsx, example/pages/container.tsx, package.json, src/component/drawer.tsx, src/form.tsx
Example http://fe.jimu.io/meson-form/#drawer
=> added a basic form drawer implementation; alpha release

example/forms/inline-form.tsx, package.json, src/inline-form.tsx
http://fe.jimu.io/meson-form/#inline-form
=> render custom type for inline form; alpha release

package.json, src/form.tsx, src/model/types.ts
https://www.teambition.com/task/5cb5ca2ac5a49600188b6100
=> add selectProps for Select component; alpha release

example/forms/drawer.tsx, package.json, src/component/drawer.tsx, src/form.tsx
Demo http://fe.jimu.io/meson-form/#drawer
New property `headerClass` for adding styles in drawers.
=> add headerClass in drawer; alpha release

example/forms/custom-multiple.tsx, src/hook/meson-core.ts, src/model/types.ts
1. `EMesonFieldType.CustomMultiple`更新泛型；
2. `validateMultiple`选填。
=> `IMesonCustomMultipleField`类型更新泛型等

example/pages/container.tsx, package.json, yarn.lock
Previews at http://fe.jimu.io/meson-form/#/home . Get a better sidebar.
=> use a richer sidebar

example/forms/modal.tsx, package.json, src/component/modal.tsx, src/util/event.ts
* use `disableMoving` if you want to disable drag-moving.
Previews http://fe.jimu.io/meson-form/#/modal
=> support drag-moving in modal; alpha release

README.md, example/controller/generated-router.ts, example/forms/decorative.tsx, example/models/router-rules.ts, example/pages/container.tsx, src/form.tsx, src/inline-form.tsx, src/model/types.ts, src/renderer.tsx, src/util/render.ts
```
type: EMesonFieldType.Decorative
```
[FR-141](https://www.teambition.com/task/5d562e0b00de490019da09c0)
=> 单个表单允许中间穿插自定义装饰Node（`Decorative`） 

example/controller/generated-router.ts, example/forms/no-label.tsx, example/models/router-rules.ts, example/pages/container.tsx, src/form-forwarded.tsx, src/form.tsx, src/inline-form.tsx, src/model/types.ts, src/renderer.tsx
1. form props: 
```
<MesonForm noLabel={true} ...rest />
```
2. `IMesonFieldBaseProps`
```
{
type: EMesonFieldType.Input,
name: "name",
label: "Name",
hideLabel: true
},
```
[FR-143](https://www.teambition.com/task/5d562e3a053f480018198f82)
=> 添加无 label 的布局

README.md, example/forms/auto-save.tsx, src/form-forwarded.tsx, src/form.tsx, src/renderer.tsx
1. 修复 Switch 在`auto-save`失效问题；
2. 扩展`auto-save`案例（switch, select）；
3. 更新README form props文档。
=> 修复 Switch 在`auto-save`失效问题

README.md, example/forms/group.tsx, example/forms/no-label.tsx, example/forms/validation.tsx, src/form-forwarded.tsx, src/form.tsx, src/model/types.ts, src/renderer.tsx
```js
// IMesonFieldItem
{
type: EMesonFieldType.Group,
contentInline: true,
children: [...],
}
```
[FR-142](https://www.teambition.com/task/5d562e2e7abc500018bdfe23)
preview [0.2.10-a1](https://www.npmjs.com/package/@jimengio/meson-form/v/0.2.10-a1)
=> 允许Group行内的横向布局

src/form.tsx
`IMesonFormModalProps`
`IMesonFormDrawerPorps`
`IMesonFormDropdownProps`
=> 同步MesonFormModal、MesonFormDrawer与MesonFormDropdown 父类props

README.md, example/forms/validation.tsx, src/form-forwarded.tsx, src/form.tsx, src/renderer.tsx
```js
// form props
<MesonForm errorClassName={...} ...rest />
```
**FieldItem:**
before: 
`margin-bottom: 16px`;
now:  
`margin-bottom: 16px;` (normal)  
`margin-bottom: 0;`(error)
npm preview [0.2.10-a3](https://www.npmjs.com/package/@jimengio/meson-form/v/0.2.10-a3)
=> 暴露verification容器className

example/controller/generated-router.ts, example/forms/login-validations.tsx, example/models/router-rules.ts, example/pages/container.tsx, package.json, src/form-forwarded.tsx, src/form.tsx, src/hook/meson-core.ts, src/model/types.ts, src/renderer.tsx, src/util/validation.ts
Changes to Input fields:
```ts
{
type: EMesonFieldType.Input,
name: "a",
// turn on checking every content change
checkOnChange: true,
// pass `formValue` as the last arguement
validator: (value, item, formValue) => {
return ""
}
}
```
Previews http://fe.jimu.io/meson-form/#/login-validations
=> FR-148 add checkOnChange on Input fields; pass form value as 3rd parameter

example/controller/generated-router.ts, package.json, yarn.lock
基于 https://github.com/jimengio/router-code-generator/pull/10 的修改.
=> upgrade router-code-generator

README.md, example/forms/forward-form.tsx
Previews http://fe.jimu.io/meson-form/#/forward-form
=> suggest using useMesonItems instead of ref forwarding

README.md, example/controller/generated-router.ts, example/forms/radio.tsx, example/models/router-rules.ts, example/pages/container.tsx, src/form.tsx, src/inline-form.tsx, src/model/types.ts, src/renderer.tsx
No test/lint/format found in workflow?
=> Simple radio button implemention

example/forms/use-items.tsx
Previews http://fe.jimu.io/meson-form/#/use-items .
=> doc: more details about formInternals from Hooks API

example/forms/modify-on-change.tsx
http://fe.jimu.io/meson-form/#/modify-on-change
=> doc: intro about onChange hook

package.json, src/form.tsx
跟设计师确认了, 16px. 原来加了额外 padding 的地方要处理一下.
=> switching to padding 16px; alpha release

example/forms/use-items.tsx, src/form.tsx
增加了 `formInternals.resetForm(data)` 方便在业务当中开启新的 form 编辑.
=> add resetForm API; alpha release

example/controller/generated-router.ts, example/forms/filter-form.tsx, example/models/router-rules.ts, example/pages/container.tsx, package.json, src/filter-form/core.tsx, src/filter-form/renderder.tsx, src/filter-form/types.tsx
=> dev: add filter form

example/forms/login-validations.tsx, package.json, src/form-forwarded.tsx, src/form.tsx, src/hook/meson-core.ts, src/inline-form.tsx, src/model/types.ts, src/renderer.tsx, src/util/render.ts
close [PK-151](https://jira.jimu.io/browse/PK-151)
=> Feat: IMesonFieldItem.name `any` -> `keyof T`

example/forms/modify-on-change.tsx, example/forms/tree-select.tsx, package.json, src/filter-form/core.tsx, src/form-forwarded.tsx, src/form.tsx, src/hook/meson-core.ts, src/model/types.ts, src/renderer.tsx, yarn.lock
改进了一下 `onChange` 参数, 提供 `internals.formData` 用于访问数据.
增加了 `dropdown-tree` 类型, 跟 antd 样式有区别:
=> Dropdown tree

package.json, src/model/types.ts
=> fix type for renderMultiple

example/controller/generated-router.ts, example/forms/input-suffix.tsx, example/main.tsx, example/models/router-rules.ts, example/pages/container.tsx, package.json, src/model/types.ts, src/renderer.tsx
目前只是对 input 和 number 增加了 suffix. 感觉功能不够通用.
=> add suffixNode in input and number

src/renderer.tsx
原来的实现问题在于 props 当中数据变化的时候这个 count 不会更新. 现在改成无状态的.
=> simplify text counting in textarea

package.json, src/form-forwarded.tsx, src/model/types.ts, src/style.ts
Disabled 元素不应该有 hover 效果, 做了一下特殊处理.
同步了一下其他分支的更新.
=> fix disabled styles; fix dropdown-select literal; copy params changes

example/controller/generated-router.ts, example/models/router-rules.ts, example/pages/container.tsx, example/pages/preview-mode.tsx, package.json, yarn.lock
基本功能是监听 postMessage 事件, 然后渲染一个 form 的样子出来. 嵌入其他 iframe 用于开发展示.
=> add a preview mode for dev purpose

example/pages/custom-theme.tsx, package.json, src/filter-form/renderer.tsx
* 修复 FilterForm 的主题设置逻辑.
* 文档少量补充.
=> fix theme insertion in filter-form; refine docs

src/component/footer-buttons.tsx, src/component/form-footer.tsx, src/filter-form/core.tsx, src/form.tsx, src/renderer.tsx, yarn.lock
方便自动化测试抓取..
- `data-area` 表单区域, 默认为 `meson-form`.
- `data-error-field` 错误区域, 值为 `item.name`.
已有属性,
- `data-field`, 值为 `item.name`.
=> adding data hooks for error-field and areas

package.json, src/filter-form/core.tsx, src/filter-form/types.tsx, src/form-forwarded.tsx, src/form.tsx, src/model/types.ts, src/util/render.ts
`onlyShow` 就是 `shouldHide` 的 not 的功能.
=> add onlyShow as an alternative of shouldHide

example/controller/generated-router.ts, example/models/router-rules.ts, example/pages/container.tsx, example/pages/debounced-input.tsx, package.json, src/component/debounced-input.tsx
jimo-ui 导致挺多问题的, 打算退回到原先组件分离的使用方案. 基础组件时不时会有更新, 用多合一的方式维护, 不适合具体项目灵活使用.
=> move debounced-input inside

package.json, src/form-forwarded.tsx, src/form.tsx, src/renderer.tsx, yarn.lock
=> upgrade flex-styles; legacy release

example/forms/async-validation.tsx, example/pages/container.tsx, example/pages/preview-mode.tsx, src/filter-form/core.tsx, src/form-forwarded.tsx, src/form.tsx, src/hook/meson-core.ts, src/inline-form.tsx, src/registered-renderer.tsx, src/renderer.tsx, src/util/data.ts, src/util/event.ts, tsconfig-compile.json, tsconfig-node.json, tsconfig.json, yarn.lock
出现很多
```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Partial<Record<FieldName<T>, string>> | Set<unknown> | Map<unknown, unknown> | (Function & Partial<Record<FieldName<T>, string>>) | ... 8 more ...
```
没弄清楚怎么处理, 用了很多的 any.
=> turn on noImplicitAny; upgrade deps

example/forms/async-validation.tsx, package.json, src/hook/meson-core.ts, src/util/render.ts
https://jira.jimu.io/browse/JM-8032
=> fix: 表单提交异步验证失效问题
