jimengio/meson-form

- package.json
- src/component/modal.tsx
Using a squared header to fix new design.
> switching to squared modal header; release 0.1.1-a2

- example/pages/container.tsx
- package.json
- src/form.tsx
- src/model/types.ts
* New type. Fragment is like group, but it has no label. It's children are rendered in the same level of current form.
* Pass current `form` to render function in type `Custom`.
> Support fragment type

- example/pages/container.tsx
- package.json
- src/form.tsx
- src/model/types.ts
表单容易宽度缩小时, Custom renderer 当中渲染的内容也要跟着变小, 所以用了 Flexbox 加上  `overflow:hidden`.
由于 antd input 默认有 `width:100%`, 还得用普通的 inline block 进行重置... 导致结构挺复杂的...
> layout changes; use a special container for Custom value renderer

- README.md
- example/controller/generated-router.ts
- example/forms/wrap-meson-core.tsx
- example/models/router-rules.ts
- example/pages/container.tsx
- package.json
- src/form.tsx
- src/hook/meson-core.ts
- src/model/types.ts
Demo http://fe.jimu.io/meson-form/#wrap-meson-core
`useMesonCore` is a hooks for maintaining states of the form. It's more reusable than form components.
`useMesonCore` 用来维护 Form 的状态, 暴露出 `form`, `errors` 和操作方法, 这样 UI 部分可以在复用逻辑的情况下, 任意定制界面样式. 这里主要复用了校验的逻辑. 不过封装当中会用到一些底层 API. 一般场景还是建议封装以后再使用.
Plus, add `inputType` property to Input fields for specifying password.
> added hooks version of meson form; alpha release

- example/controller/generated-router.ts
- example/forms/forward-form.tsx
- example/models/router-rules.ts
- example/pages/container.tsx
- src/form.tsx
MesonForm组件对其父组件（即：容器组件）开放onSubmit、onReset api; 父组件可以通过Form组件的ref去调用form的onSubmit、onReset；
```ts
const formRef = React.useRef<MesonFormHandler>(null);
<MesonForm
ref={formRef}
hideFooter
onSubmit={(form) => {
console.log("form data: ", form);
}}
onReset={() => {
}}
/>
formRef.current.onSubmit();
formRef.current.onReset();
```
> add useImperativeHandle in MesonForm

- example/controller/generated-router.ts
- example/forms/basic.tsx
- example/forms/custom.tsx
- example/forms/forward-form.tsx
- example/forms/modify-on-change.tsx
- example/models/router-rules.ts
- example/pages/container.tsx
- package.json
- src/form.tsx
- src/model/types.ts
* Support modifying form with function on change event. Demo http://fe.jimu.io/meson-form/#modify-on-change
* Transform empty string to `undefined` for inputs by default. This behavior can be changed by `useBlank: true`.
* Added `inputProps` for `Input` fields.
已发布 `0.1.14-a3`.
> Modify form on change

- README.md
- example/controller/generated-router.ts
- example/forms/custom-multiple.tsx
- example/forms/wrap-meson-core.tsx
- example/models/router-rules.ts
- example/pages/container.tsx
- package.json
- src/form.tsx
- src/hook/meson-core.ts
- src/inline-form.tsx
- src/model/types.ts
- src/util/render.ts
- src/util/validation.ts
Example http://fe.jimu.io/meson-form/#custom-multiple
Designed for rendering fields linked to multiple properties. See example at https://github.com/jimengio/meson-form/blob/custom-multiple/example/forms/custom-multiple.tsx#L16-L70 .
Validation should also be work even it’s related to multiple properties.
`CustomMultiple` 用于渲染一个组件对应到多个字段的 UI, 同时, 原有的提交时校验, 以及编辑完成时触发校验这个逻辑依然要正常运行. 目前的实现基本满足要求, 类型约束的细节需要后续完善.
* Some duplicated functions in `form.tsx` has been merged into `meson-core.ts` for reuse.
* Some changes on types and naming. But they should not affect users.
> Custom field for multiple properties

- README.md
- example/controller/generated-router.ts
- example/forms/draft.tsx
- example/forms/group.tsx
- example/models/router-rules.ts
- example/pages/container.tsx
- src/form.tsx
- src/inline-form.tsx
- src/model/types.ts
- src/util/render.ts
After this change:
* `Nested`, fields that nested after this field.
* `Group`, not nested, but multiple fields, designed for show/hiding multiple fields with one variable.
This is a breaking change. However it’s probably not in use yet.
> rename group type to reduce confusion

- src/component/drawer.tsx
直接用center的话，关闭icon也会一起居中...
所以加了个span空元素，然后还是沿用原来的space-between
> drawer标题居中

- package.json
- src/hook/meson-core.ts
1. 修复 `checkItem` 泛型丢失；
2. 完善 `form` `error` (immer data) 类型申明，去除多余重复申明。
> 完善 `meson-core` 类型

- src/renderer.tsx
添加属性之后在 DOM 上能定位到一个 `data-field` 属性, UI 测试的代码比较容易定位.
以及
> add data-field for testing purposes

- package.json
- src/form.tsx
- src/model/types.ts
`ValueFieldContainer` 组件的默认样式是 180px 宽度, 而且不能更改. 这个会影响到具体使用. 直接增加一个 className 用于修改.
由于不是常用的配置, 而且不同的类型可能有不同的样式需求, 所以不在 Form 组件上直接加共享的 `valueContainerClassName`. 可能出现的情况是某个特殊场景, 很多个 item 都要各自加一遍样式, 目前认为可以接受.
名称略长... 但没想到更好的.
> add valueContainerClassName; alpha release

- example/forms/use-items.tsx
- package.json
- src/form.tsx
- src/index.ts
涉及到 transition 的问题, 做过渡动画需要 formModal 提前挂载, 提前挂载的话, 内部状态需要更新, 这样就需要通过 `updateForm` 来操作了, 所以故意暴露到外面.
参考 http://fe.jimu.io/meson-form/#/use-items 当中的 "Reset name" 按钮.
> api: expose updateForm at useFormItems; alpha release

- example/forms/use-items.tsx
- example/forms/wrap-meson-core.tsx
- package.json
- src/form.tsx
- src/hook/meson-core.ts
`useFormItems` 写法中, 允许 `onCheckSubmit` 传入一个 `{onSubmit: (form) => { ... }}` 参数, 在校验通过的情况下直接调用方法处理数据. 原来的 `onSubmit` 是在 `useFormItems({..., onSubmit: (form) => { ... }})` 当中写的.
目前只是作为一个探索性的写法, 逻辑可能会更清晰一点, 不确定优劣.
文档 http://fe.jimu.io/meson-form/#/use-items .
> add onSubmit options on onCheckSubmit method; alpha release

- example/forms/validation.tsx
- package.json
- src/lingual/locales.edn
- src/lingual/zh-cn.ts
- src/util/validation.ts
原先的逻辑, `validator` 方法存在的时候, `required` 属性的行为就被跳过了.. 设定的逻辑是只有要 required, 数据就不可以为 `null` 为 `""` 的.
> ensure required rule used even validator exists

- README.md
- example/forms/use-items.tsx
- example/pages/container.tsx
- src/form-forwarded.tsx
- src/form.tsx
- src/hook/meson-core.ts
- src/index.ts
- src/inline-form.tsx
`useMesonItems` 用的数组作为返回结果, 随着功能扩展, 使用不够方便, 后面加了 `formInternals` 强行暴露多个方法/属性, 现在用 `useMesonFields` 统一成对象的写法. 原先的写法, 兼容也是在的.
`transferData` 是为了修复传递上下文的问题, 比如这样一个写法, 上下文 `item.id` 无法直接传到 submit 的地方去, 简单粗暴的结构是用 `useRef` 临时存储,
```js
let fieldsPlugin = useMesonFields({
initialValue: {},
items: formItems,
onSubmit: (form) => {
console.log('After validation:', form);
},
});
data.map(item => {
return <div onClick={() => {
// 上下文 item.id 
fieldsPlugin.checkAndSubmit()
}}>
</div>
})
```
现在强行加上一个 `transferData`, 传递到 `onSubmit` 的位置, 实现有点乱, 至少能传递过去了.
```js
let transferPlugin = useMesonFields<any, string>({
initialValue: form,
items: formItems,
onSubmit: (form, _, transferData) => {
console.log(form, transferData);
},
});
data.map(item => {
return <div onClick={() => {
// 上下文 item.id …
```
> feature: add useMesonFields; support passing transferData

- package.json
- src/hook/meson-core.ts
> fix null options.transferData 

- package.json
- src/filter-form/core.tsx
- src/renderer.tsx
遇到半像素的情况, box-shadow 显示不正常并且伴随抖动, 基本认为跟 overflow 遮挡有关, 而且容器位置半像素的情况容易出现.
去除 overflow auto 大致看下来布局还是正常, 需要担心某些特殊布局会不会有影响风险.
> fix textarea half pixel box shadow flicking in chrome

- example/controller/generated-router.ts
- example/forms/async-validation.tsx
- example/models/router-rules.ts
- example/pages/container.tsx
- src/hook/meson-core.ts
- src/model/types.ts
- src/util/data.ts
基础功能的异步校验支持. 单个表单项编辑完成时会触发一次异步校验.
当前实现不包含一些相关的功能,
* submit 时的校验只检查同步的 `validator` 方法, 而不会检查异步的 `asyncValidator`.
* 异步校验进行时, 不会有 loading 提示.
完整的功能涉及到的代码较多, 可能与已有的某些特殊功能冲突, 后续再考虑了. 暂时只对基础的异步校验增加支持.
> very initial solution for async validation

- example/controller/generated-router.ts
- example/forms/registered-renderer.tsx
- example/models/router-rules.ts
- example/pages/container.tsx
- src/form.tsx
- src/index.ts
- src/model/types.ts
- src/registered-renderer.tsx
Previews http://fe.jimu.io/meson-form/#/registered-renderer .
* 新增 API `registerMesonFormRenderer`
* 选择类型 `registered` 对应 `renderType` 和 `renderOptions` 这些属性.
大致对应 https://github.com/jimengio/rough-table/pull/69 . 允许业务做全局配置. 同样的动态类型的一些缺陷.
> basic support for registered render

- example/forms/draft.tsx
- example/forms/group.tsx
- example/forms/wrap-meson-core.tsx
- package.json
- src/model/types.ts
- src/util/validation.ts
- yarn.lock
以往的 `validateMethods` 过于粗糙, 业务当中没有在使用. 目前使用的是 `validator` 方法. 参考用例改成了 `validateRules` 的规则, 具体使用规则参考 https://github.com/jimengio/ruled-validator/blob/master/src/validate.test.ts .
> remove validateMethods, make use of validateRules

- src/form.tsx
> mark useMesonItems as deprecated
